NEW Create GraphQLSchemaInitTask
silverstripe/silverstripe-graphql-devtools pull request #53
Opened 2024-04-09 07:09 UTC by emteknetnz

Issue https://github.com/silverstripe/silverstripe-graphql-devtools/issues/45

Replaces https://github.com/silverstripe/silverstripe-graphql/pull/433

2024-04-14 19:35 UTC, sabina-talipova requested changes

2024-04-14 19:35 UTC, sabina-talipova commented on README.md
> +
Could we add expected result of execution of this task in this section if it's not mentioned somewhere else. Then developers can check that they get  all required files.

2024-04-14 19:35 UTC, sabina-talipova commented on README.md
GraphQLSchemaInitTask expects get some optional request parameters, like `graphqlConfigDir`, `endpoint`, etc. User can get them from `help`, but If they are important or they somehow can impact to result, probably it's better to mention them here.

2024-04-14 19:35 UTC, sabina-talipova commented on src/GraphQLSchemaInitTask.php
> +
Is there any way how we can improve this? Probably add some spaces... It's not so easy to read in small terminal window.

2024-04-14 19:35 UTC, sabina-talipova commented on src/GraphQLSchemaInitTask.php
> +        }
Just for clarification. We don't do anything if `GraphQL` folder exists, even if this folder is empty, right?
So it means, that we can finish all previous steps and create all files, but don't create `Resolver`.

2024-04-14 19:35 UTC, sabina-talipova commented on src/GraphQLSchemaInitTask.php
> +        $this->createResolvers();
Probably, we should add checker before all steps to check if there are files or directories in the project in folders in which task will create new files with the same names then provide warning that some files or dirs should not be there.

2024-04-15 03:26 UTC, emteknetnz commented on README.md
> +
Added

2024-04-15 03:27 UTC, emteknetnz commented on README.md
I've changed it around to prompt them to view help first before running the task.  I haven't added all the options in the README because it's basically just duplicating documentation since it's already in the help section

2024-04-15 03:28 UTC, emteknetnz commented on src/GraphQLSchemaInitTask.php
> +        $this->createResolvers();
These methods will already echo out if there are existing directories and will say that it's skipping

2024-04-15 03:29 UTC, emteknetnz commented on src/GraphQLSchemaInitTask.php
> +        }
Correct. This seems like a good behavior IMO

2024-04-15 03:31 UTC, emteknetnz commented on src/GraphQLSchemaInitTask.php
> +
I've changed it to use linebreaks, seems more readable now

2024-04-15 19:57 UTC, sabina-talipova approved these changes
LGTM. It was tested locally. It works perfect.

2024-04-15 19:58 UTC, merged